[
    {
        "content": "<p>I've updated the QI-Core IG resource to reference the VSAC package:</p>\n<p><a href=\"/user_uploads/10155/L6Hzi0LsTtA7lEs5IOIiLCco/Screen-Shot-2021-10-22-at-5.19.32-PM.png\">IG resource</a> </p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/10155/L6Hzi0LsTtA7lEs5IOIiLCco/Screen-Shot-2021-10-22-at-5.19.32-PM.png\" title=\"IG resource\"><img src=\"/user_uploads/10155/L6Hzi0LsTtA7lEs5IOIiLCco/Screen-Shot-2021-10-22-at-5.19.32-PM.png\"></a></div><p>Still getting the following errors with being \"unable to find the value set\"</p>\n<p><a href=\"/user_uploads/10155/xV7tMR3Pe-qzakGy5ThXVYiJ/Screen-Shot-2021-10-12-at-3.23.39-PM.png\">Error</a> </p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/10155/xV7tMR3Pe-qzakGy5ThXVYiJ/Screen-Shot-2021-10-12-at-3.23.39-PM.png\" title=\"Error\"><img src=\"/user_uploads/10155/xV7tMR3Pe-qzakGy5ThXVYiJ/Screen-Shot-2021-10-12-at-3.23.39-PM.png\"></a></div><p>Any suggestions as a next step to resolve the error?</p>",
        "id": 259099354,
        "sender_full_name": "Abdullah Rafiqi",
        "timestamp": 1635256464
    },
    {
        "content": "<p>I think the latest package is 0.4.0? But it's pretty old (I'm thinking January?) so if your value set is more recent than that it likely won't be in the package.</p>",
        "id": 259179264,
        "sender_full_name": "Sarah Gaunt",
        "timestamp": 1635294074
    },
    {
        "content": "<p>Though I can actually see that <a href=\"http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1021.56\">http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1021.56</a> is in 0.4.0</p>",
        "id": 259179366,
        "sender_full_name": "Sarah Gaunt",
        "timestamp": 1635294163
    }
]