[
    {
        "content": "<p>I'm using the .NET API to undertake a simple \"GET\" request  via</p>\n<div class=\"codehilite\"><pre><span></span>        try\n        {\n               Organization xx = client.Read&lt;Organization&gt;(url);\n        }\n        catch (Exception e)\n        {\n               throw;\n        }\n</pre></div>\n\n\n<p>In situations where the resource does not exist (i.e. a 404) an exception is thrown - in this case how do I get the HTTP response code?</p>",
        "id": 153928357,
        "sender_full_name": "Richard Kavanagh",
        "timestamp": 1515626063
    },
    {
        "content": "<p>The exception you are catching is actually a FhirOperationException, so you could split your try/catch like so:</p>\n<div class=\"codehilite\"><pre><span></span>try\n{\n}\ncatch(FhirOperationException foe)\n{\n        // inspect status\n        var httpStatus = foe.Status;\n\n         // get even more details\n        var operationOutcome = foe.Outcome;\n\n}\ncatch(Exception e)\n{\n   // something *really* bad happened\n}\n</pre></div>",
        "id": 153928389,
        "sender_full_name": "Ewout Kramer",
        "timestamp": 1515661420
    },
    {
        "content": "<p>Perfect - thanks</p>",
        "id": 153928403,
        "sender_full_name": "Richard Kavanagh",
        "timestamp": 1515665278
    }
]