[
    {
        "content": "<p>I   have been seeing incorrect errors when validating QuestionnaireResponses against Questionnaires, with the validator wrongly claiming that an answer code is not in the appropriate value set. The error message is this:</p>\n<div class=\"codehilite\"><pre><span></span><code>  Error @ QuestionnaireResponse.item[0].answer[0] (line 10, col68) : The value provided (http://loinc.org::LA32-8) is not in the options value set in the questionnaire\n</code></pre></div>\n<p>I know this has been discussed in other threads, but so far I have not found smt. that solves my variant of the issue (please correct me on that if I'm wrong <span aria-label=\"smile\" class=\"emoji emoji-1f642\" role=\"img\" title=\"smile\">:smile:</span> ). Here is a minimal set of resources that reproduces the problem</p>\n<ol>\n<li>A Questionnaire with two coded questions, both using the same answer value set  - <a href=\"/user_uploads/10155/16kcGI4O2P-9bfTbz7w07LXO/qr.questionnaireresponse.json\">qr.questionnaireresponse.json</a></li>\n<li>The value set (containing two LOINC codes)  -  <a href=\"/user_uploads/10155/KADmBOYBTuEYjQt4z0SCoSoH/yesno.ValueSet.json\">yesno.ValueSet.json</a> </li>\n<li>And QuestionnaireResponse causing the above error although both codes are from the value set - <a href=\"/user_uploads/10155/B_8xPzr9E3_2cfqDnGKEA5XQ/q.questionnaire.json\">q.questionnaire.json</a></li>\n</ol>\n<p>To get the error, put 1 &amp; 2 in the same folder, load them in the validator with the <code>-ig</code> parameter pointing to the folder, and validate the Questionnaire response.</p>\n<p>Curiously, the error only appears if the two questions are answered with <em>different codes</em> - if I modify the example to use the <em>same</em> code in both answers, it validates OK. However, I know that others have seen the same error for questionnaires containing only a single coded question, at least when using codes from a custom CodeSystem (<span class=\"user-mention\" data-user-id=\"327858\">@Christian Nau</span> FYI).</p>",
        "id": 226372015,
        "sender_full_name": "Morten Ernebjerg",
        "timestamp": 1613388393
    },
    {
        "content": "<p>I've tested your example files with validation agianst HAPI FHIR &amp; SmileCDR servers:<br>\n(using <code>{base-url/QuestionnaireResponse/$validate</code>)</p>\n<ul>\n<li>HAPI FHIR: got the <code>The value provided (http://loinc.org::LA33-6) is not in the options value set in the questionnaire</code> error no matter if both ansers do have the same code or not.</li>\n<li>Smile CDR: validation succeeded.</li>\n</ul>\n<p>For my use-case, as <span class=\"user-mention\" data-user-id=\"194703\">@Morten Ernebjerg</span> wrote, I have a custom-code-system, custom-value-set with a very simple Questionnaire, with only one coded answer that has a value-set-binding to the custom-code-system. The answer inside QuestionnaireResponse refers to the custom-code- system. There I get the same error mentioned above (for HAPI FHIR and for Smile CDR). </p>\n<p>The strange thing is: from time to time the validation succeeds without me changing anything in Questionnaire/CodeSystem/ValueSet.</p>\n<p>I also didn't manage to reproduce this in a minimal working example.<br>\n<em>I have the feeling that this may be related to updated Questionnaires.</em></p>",
        "id": 226381367,
        "sender_full_name": "Christian Nau",
        "timestamp": 1613394392
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"248736\">@Mark Iantorno</span> Do you have an idea why this might be happening - or should we raise this issue in another forum/channel?</p>",
        "id": 226777312,
        "sender_full_name": "Morten Ernebjerg",
        "timestamp": 1613636231
    },
    {
        "content": "<p>I do not know offhand why this is occuring. I will _try_ to look at this at some point today. However, I'm pretty much booked solid already, and I am off tomorrow...so it may have to wait until next week. In the meantime, could you please open an issue on Github with all the details and assign to me?</p>",
        "id": 226808691,
        "sender_full_name": "Mark Iantorno",
        "timestamp": 1613654746
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"248736\">@Mark Iantorno</span>  Sure , thanks! This is not a super-urgent issue for me, BTW.</p>",
        "id": 226809070,
        "sender_full_name": "Morten Ernebjerg",
        "timestamp": 1613654938
    },
    {
        "content": "<p>Which github repo?</p>",
        "id": 226809249,
        "sender_full_name": "Morten Ernebjerg",
        "timestamp": 1613655024
    },
    {
        "content": "<p>I dug a little deeper into this issue. Found out together with <span class=\"user-mention\" data-user-id=\"191451\">@Patrick Werner</span> that this is happening once I updated my code-system and value-set to overwrite existing code values with new ones (fixed casing of experimental systems..) Maybe <span class=\"user-mention\" data-user-id=\"191451\">@Patrick Werner</span> can elaborate on this in more depth.</p>",
        "id": 226809871,
        "sender_full_name": "Christian Nau",
        "timestamp": 1613655332
    },
    {
        "content": "<p>I think the reason behind is that during a CS Update the VS expansion didn't get regenerated.</p>",
        "id": 226811693,
        "sender_full_name": "Patrick Werner",
        "timestamp": 1613656135
    },
    {
        "content": "<p>So the expansion contains old and maybe deprecated concept codes.</p>",
        "id": 226811746,
        "sender_full_name": "Patrick Werner",
        "timestamp": 1613656162
    },
    {
        "content": "<p>but <span class=\"user-mention\" data-user-id=\"194703\">@Morten Ernebjerg</span> issue is independent of the hapi server.</p>",
        "id": 226816764,
        "sender_full_name": "Patrick Werner",
        "timestamp": 1613658291
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"194703\">@Morten Ernebjerg</span> issues for the Validator should go into here: <a href=\"https://github.com/hapifhir/org.hl7.fhir.core/issues\">https://github.com/hapifhir/org.hl7.fhir.core/issues</a></p>",
        "id": 226816841,
        "sender_full_name": "Patrick Werner",
        "timestamp": 1613658322
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"248736\">@Mark Iantorno</span>  I put in a GitHub issue (<a href=\"https://github.com/hapifhir/org.hl7.fhir.core/issues/441\">https://github.com/hapifhir/org.hl7.fhir.core/issues/441</a>). Unfortunately, it seems I do not have the right to assign it to you.</p>",
        "id": 226819206,
        "sender_full_name": "Morten Ernebjerg",
        "timestamp": 1613659236
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"194703\">@Morten Ernebjerg</span> i did the assign, thanks for the issue</p>",
        "id": 226821717,
        "sender_full_name": "Patrick Werner",
        "timestamp": 1613660153
    },
    {
        "content": "<p>ok fixed next release</p>",
        "id": 227535449,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1614131120
    },
    {
        "content": "<p>Thanks, <span class=\"user-mention\" data-user-id=\"191316\">@Grahame Grieve</span>! - do you want the example as a PR for the test case GitHub repo?</p>",
        "id": 227570502,
        "sender_full_name": "Morten Ernebjerg",
        "timestamp": 1614158872
    },
    {
        "content": "<p>already added</p>",
        "id": 227664692,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1614197871
    }
]