[
    {
        "content": "<p>I\"m getting the following error on IG build:</p>\n<p>The code \"95420-6\" is not valid in the system <a href=\"http://loinc.org\">http://loinc.org</a>; The code provided (http://loinc.org#95420-6) is not valid in the value set 'All codes known to the system' (from <a href=\"http://tx.fhir.org/r4\">http://tx.fhir.org/r4</a>) for 'http://loinc.org#95420-6'</p>\n<p>However, <a href=\"https://loinc.org/95420-6/\">https://loinc.org/95420-6/</a> exists.  So, how do I/we/you/they get this added?</p>",
        "id": 223132550,
        "sender_full_name": "David Pyke",
        "timestamp": 1610983078
    },
    {
        "content": "<p>I also get a lot of warnings about other missing codes, but this is the only error.  The rest are COVID tests and I'm assuming they haven't been added yet.</p>",
        "id": 223133077,
        "sender_full_name": "David Pyke",
        "timestamp": 1610983297
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"192587\">@David Pyke</span> Can you confirm that another code that was introduced with the current 2.69 release is <strong>not</strong> causing an error? Likely another COVID-19 code?</p>",
        "id": 223141008,
        "sender_full_name": "Robert McClure",
        "timestamp": 1610987302
    },
    {
        "content": "<p>Can you link me to the codes that were added with 2.69?</p>",
        "id": 223141098,
        "sender_full_name": "David Pyke",
        "timestamp": 1610987372
    },
    {
        "content": "<p>Many of these <a href=\"https://loinc.org/sars-cov-2-and-covid-19/\">here</a> such as <a href=\"https://loinc.org/95418-0/\">95418-0</a></p>",
        "id": 223141400,
        "sender_full_name": "Robert McClure",
        "timestamp": 1610987540
    },
    {
        "content": "<p>Yes, I have almost all of those in my ValueSets, I get a bunch of warnings but this is the only error</p>",
        "id": 223141650,
        "sender_full_name": "David Pyke",
        "timestamp": 1610987704
    },
    {
        "content": "<p><a href=\"/user_uploads/10155/-SjZG-3lmXpXgSfa_BJWet2h/qa.txt\">qa.txt</a>   Has all the details</p>",
        "id": 223141886,
        "sender_full_name": "David Pyke",
        "timestamp": 1610987846
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"191316\">@Grahame Grieve</span> <span class=\"user-mention\" data-user-id=\"191405\">@Rob Hausam</span></p>",
        "id": 223154192,
        "sender_full_name": "Robert McClure",
        "timestamp": 1610996324
    },
    {
        "content": "<p>I don't know. When was it added?</p>",
        "id": 223213726,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1611055583
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"192587\">@David Pyke</span>  We haven't updated the server to LOINC 2.69 yet.  I'll do that this morning.</p>",
        "id": 223226667,
        "sender_full_name": "Rob Hausam",
        "timestamp": 1611063649
    },
    {
        "content": "<p>Unfortunately, there's a problem with the import for LOINC 2.69.  I'm investigating.</p>",
        "id": 223261536,
        "sender_full_name": "Rob Hausam",
        "timestamp": 1611077490
    },
    {
        "content": "<p>Has the problem been fixed?</p>",
        "id": 223892099,
        "sender_full_name": "David Pyke",
        "timestamp": 1611579221
    },
    {
        "content": "<p>I still seem to be getting these errors, is there a step I'm missing?</p>",
        "id": 224349002,
        "sender_full_name": "David Pyke",
        "timestamp": 1611850266
    },
    {
        "content": "<p>No, it hasn't been fixed yet - but it should be soon.  I've had to do some other work to be able to find and fix the error in the import, which I'm now about to attempt to do.</p>",
        "id": 224434285,
        "sender_full_name": "Rob Hausam",
        "timestamp": 1611900699
    },
    {
        "content": "<p>I'm still seeing this error, as well</p>",
        "id": 230883450,
        "sender_full_name": "David Pyke",
        "timestamp": 1616081314
    },
    {
        "content": "<p>The same answer here, of course - still need to resolve the LOINC 2.69 import bug.</p>",
        "id": 230884071,
        "sender_full_name": "Rob Hausam",
        "timestamp": 1616081510
    },
    {
        "content": "<p>I'll try it again today - maybe it will magically work this time. :)</p>",
        "id": 230884218,
        "sender_full_name": "Rob Hausam",
        "timestamp": 1616081552
    },
    {
        "content": "<p>And did it?  This is worrisome that we don't have the COVID codes loaded with so many projects using them</p>",
        "id": 231311161,
        "sender_full_name": "David Pyke",
        "timestamp": 1616420431
    },
    {
        "content": "<p>Well, I didn't quite get to it \"today\" (Thurs. 18th).  Let me see if I can try it now - during the Vocab call. :)</p>",
        "id": 231392175,
        "sender_full_name": "Rob Hausam",
        "timestamp": 1616450799
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"192587\">@David Pyke</span> The issue is still there (no surprise).  It's choking on an issue with \"order/obs\" and the value 'Y' (which I believe likely hasn't been in the data previously - and I assume is intentional?).  This is still going to require a (likely fairly small?) code change in the importer to resolve (hopefully we will be able to get that done soon - I agree it's certainly a priority).</p>",
        "id": 231394220,
        "sender_full_name": "Rob Hausam",
        "timestamp": 1616452046
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"191405\">@Rob Hausam</span> Did this get fixed?  I'm getting the same error for a different LOINC Code that is also included in 2.69 (<a href=\"https://loinc.org/96315-7/\">https://loinc.org/96315-7/</a>):</p>\n<div class=\"codehilite\"><pre><span></span><code>The code &quot;96315-7&quot; is not valid in the system http://loinc.org\n</code></pre></div>\n<p><a href=\"/user_uploads/10155/uwl5aLkJMCrCUB9Olxv6cA7C/image.png\">image.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/10155/uwl5aLkJMCrCUB9Olxv6cA7C/image.png\" title=\"image.png\"><img src=\"/user_uploads/10155/uwl5aLkJMCrCUB9Olxv6cA7C/image.png\"></a></div>",
        "id": 233165210,
        "sender_full_name": "Rob Reynolds",
        "timestamp": 1617625507
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"217210\">@Rob Reynolds</span> Unfortunately, this hasn't been fixed yet.  <span class=\"user-mention\" data-user-id=\"322501\">@Max Masnick</span> has also been asking about it (<a href=\"#narrow/stream/179202-terminology/topic/LOINC.20COVID.20test.20codes.3F\">here</a>).  I thought I might be able to work around the problem by massaging the LOINC source data, but when I looked at that there seems to be nothing in the data that would be causing this error that can be adjusted.  So it's looking like the code does really need to be fixed, and I need to get back to fixing the one blocker in my environment for compiling the Pascal source so that I can do that.  I'll see if I can take another look at that today and hopefully can make some progress on it.</p>",
        "id": 233172851,
        "sender_full_name": "Rob Hausam",
        "timestamp": 1617629999
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"191405\">@Rob Hausam</span> Thank you for the update!  Good luck with fixing your environment.  I hate those kinds of issues.</p>",
        "id": 233194907,
        "sender_full_name": "Rob Reynolds",
        "timestamp": 1617639719
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"191405\">@Rob Hausam</span>  To quote <span class=\"user-mention\" data-user-id=\"192119\">@Yan Heras</span>  (from the UTG thread <a href=\"https://jira.hl7.org/browse/UP-175?focusedCommentId=185035&amp;page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-185035\">https://jira.hl7.org/browse/UP-175?focusedCommentId=185035&amp;page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-185035</a>)</p>\n<blockquote>\n<p>[W]e are planning to start the publication process for the Data Exchange for Quality Measure IG (<a href=\"http://build.fhir.org/ig/HL7/davinci-deqm/\">http://build.fhir.org/ig/HL7/davinci-deqm/</a>) very soon. Our only remaining QA errors are generated by needing this new ActCode <strong>and also a new valid LOINC code for gaps in care report that we requested for this IG is not recognized by the IG publisher. So this is an immediate blocker for us.</strong></p>\n</blockquote>\n<p>Given that, thoughts on the likelihood of it being fixed soon?  I know this has been an issue for months and it's being tracked by a number of other folks who are also experiencing issues with it, so... just trying to plan as best as we can for the above.</p>",
        "id": 233469896,
        "sender_full_name": "Rob Reynolds",
        "timestamp": 1617794345
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"191405\">@Rob Hausam</span> It's fixed!!!  Woot!!!</p>",
        "id": 237311823,
        "sender_full_name": "Rob Reynolds",
        "timestamp": 1620130158
    },
    {
        "content": "<p>Yes, I was able finally to get that done!</p>",
        "id": 237314709,
        "sender_full_name": "Rob Hausam",
        "timestamp": 1620131491
    }
]