[
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"215604\">@Saul Kravitz</span>  <br>\nSeeing url text is different than actual url in IG at many places. For example, in practitioner Role profile, for newpatients extension below url is mentioned - <br>\nNew Patients URL: <a href=\"http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/newpatients\">http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/newpatients</a></p>\n<p>But we can click on this, it opens up below url - <br>\n<a href=\"https://build.fhir.org/ig/HL7/davinci-pdex-plan-net/StructureDefinition-newpatients.html\">https://build.fhir.org/ig/HL7/davinci-pdex-plan-net/StructureDefinition-newpatients.html</a></p>\n<p>Is there any reason behind this behavior ? Noticed it at many places and this is causing FHIR Validator tool to thrwo 'URL could not resolve error'</p>\n<p>Please update what is correct and which url should be used in actual response.<br>\nThanks!!</p>",
        "id": 218838488,
        "sender_full_name": "Chetan Jain",
        "timestamp": 1607091934
    },
    {
        "content": "<p>Everything looks right to me.<br>\nThe url for the extension is <a href=\"http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/newpatients\">http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/newpatients</a>.   The url of the html page is different (Structure-definition), but that is fine.  Validator is run on all IG content without errors.</p>\n<p>Get Outlook for iOS&lt;<a href=\"https://aka.ms/o0ukef\">https://aka.ms/o0ukef</a>&gt;</p>",
        "id": 218841999,
        "sender_full_name": "Saul Kravitz",
        "timestamp": 1607093558
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"215604\">@Saul Kravitz</span>   Validator is giving errors like below -<br>\nURL value '<a href=\"http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/qualification\">http://hl7.org/fhir/us/davinci-pdex-plan-net/StructureDefinition/qualification</a>' does not resolve</p>",
        "id": 219067214,
        "sender_full_name": "Chetan Jain",
        "timestamp": 1607339477
    },
    {
        "content": "<p>Which version of the IG are you trying to validate against?</p>",
        "id": 219083043,
        "sender_full_name": "Saul Kravitz",
        "timestamp": 1607349853
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"215604\">@Saul Kravitz</span>  - Using below command  <br>\njava -jar validator_cli.jar response.json -version 4.0.1 -ig hl7.fhir.us.davinci-pdex-plan-net</p>",
        "id": 219207330,
        "sender_full_name": "Chetan Jain",
        "timestamp": 1607435042
    },
    {
        "content": "<p>Just to be sure, try adding the version number:</p>\n<p>java -jar validator_cli.jar response.json -version 4.0.1 -ig hl7.fhir.us.davinci-pdex-plan-net#1.0.0</p>",
        "id": 219211641,
        "sender_full_name": "Saul Kravitz",
        "timestamp": 1607437343
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"215604\">@Saul Kravitz</span> <br>\nGetting this error when running with IG version - </p>\n<p>Loading<br>\n  Load FHIR v4.0 from hl7.fhir.r4.core#4.0.1 - 4575 resources (00:07.0153)<br>\n  Terminology server <a href=\"http://tx.fhir.org\">http://tx.fhir.org</a> - Version 1.9.367 (00:24.0772)<br>\n2020-12-08 20:46:15.907 [main] INFO  o.h.f.u.npm.BasePackageCacheManager [BasePackageCacheManager.java:79] Failed to resolve package hl7.fhir.us.davinci-pdex-plan-net#1.0.0 from server: <a href=\"http://packages.fhir.org\">http://packages.fhir.org</a><br>\n2020-12-08 20:46:16.842 [main] INFO  o.h.f.u.npm.BasePackageCacheManager [BasePackageCacheManager.java:79] Failed to resolve package hl7.fhir.us.davinci-pdex-plan-net#1.0.0 from server: <a href=\"http://packages2.fhir.org/packages\">http://packages2.fhir.org/packages</a><br>\nException in thread \"main\" org.hl7.fhir.exceptions.FHIRException: Unable to find package hl7.fhir.us.davinci-pdex-plan-net#1.0.0<br>\n        at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.loadPackage(FilesystemPackageCacheManager.java:497)<br>\n        at org.hl7.fhir.validation.ValidationEngine.loadIg(ValidationEngine.java:1010)<br>\n        at org.hl7.fhir.validation.cli.services.ValidationService.getValidator(ValidationService.java:217)<br>\n        at org.hl7.fhir.validation.ValidatorCli.doValidation(ValidatorCli.java:159)<br>\n        at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:115)</p>\n<p>If i run without version then get below trace -</p>\n<p>Loading<br>\n  Load FHIR v4.0 from hl7.fhir.r4.core#4.0.1 - 4575 resources (00:07.0537)<br>\n  Terminology server <a href=\"http://tx.fhir.org\">http://tx.fhir.org</a> - Version 1.9.367 (00:03.0594)<br>\n  Load hl7.fhir.us.davinci-pdex-plan-net#0.1.0 - 144 resources (00:00.0116)<br>\n  Get set...  go (00:00.0153)</p>",
        "id": 219218885,
        "sender_full_name": "Chetan Jain",
        "timestamp": 1607440853
    },
    {
        "content": "<p>My interpretation:</p>\n<ul>\n<li>the 0.1.0 version is very stale</li>\n<li>the 1.0.0 version isn't available</li>\n</ul>\n<p>Try running with the version set to '#dev' instead of '#1.0.0'.<br>\nThat is the version in my package cache.   Try running the validator that way, and then look in:<br>\n<code>more ~/.fhir/packages/hl7.fhir.us.davinci-pdex-plan-net\\#dev/package/package.json</code></p>\n<p>You should see version 0.1.8 (which is the same as version 1.0.0). <span class=\"user-mention\" data-user-id=\"356642\">@Chetan Jain</span></p>",
        "id": 219222957,
        "sender_full_name": "Saul Kravitz",
        "timestamp": 1607442767
    },
    {
        "content": "<p>Thanks <span class=\"user-mention\" data-user-id=\"215604\">@Saul Kravitz</span>  pulling the dev version resolved the issue of false errors. Appreciate all your support !!</p>",
        "id": 220219518,
        "sender_full_name": "Chetan Jain",
        "timestamp": 1608195841
    }
]