[
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"191316\">@Grahame Grieve</span> said there is a new version of the fhirValidator (5.2.10). Inferno currently bundles 5.1.0 (iirc).  The later version fixes some issues with resolving URls.  We've tried just updating the build.gradle.kts to use the later dependency, </p>\n<div class=\"codehilite\"><pre><span></span><code>implementation(&quot;ca.uhn.hapi.fhir&quot;, &quot;org.hl7.fhir.validation&quot;, &quot;5.2.10&quot;)\n</code></pre></div>\n\n<p>on the  <a href=\"https://github.com/inferno-community/fhir-validator-wrapper.git\">https://github.com/inferno-community/fhir-validator-wrapper.git</a> </p>\n<p>but the docker build fails with, </p>\n<p>#16 108.1 &gt; Task :compileJava<br>\n#16 108.1 /home/src/main/java/org/mitre/inferno/Validator.java:22: error: package org.hl7.fhir.utilities.cache does not exist<br>\n#16 108.1 import org.hl7.fhir.utilities.cache.FilesystemPackageCacheManager;</p>\n<p>My gradle/maven isn't very good.  How can I update the bundled vlaidator for Inferno to use the later fhir validator?</p>\n<p>Thanks!</p>",
        "id": 219375549,
        "sender_full_name": "Marvin Greenberg",
        "timestamp": 1607537652
    },
    {
        "content": "<p>Hey <span class=\"user-mention\" data-user-id=\"267676\">@Marvin Greenberg</span>.  We do try and keep the validator dependency up to date, but it often has API changes that make it trickier than just updating the dependency version.</p>\n<p>Currently Inferno uses version <code>5.1.7</code> of the validator dependency.  It looks like <code>5.1.16</code> (<a href=\"https://github.com/hapifhir/org.hl7.fhir.core/pull/358\">see this PR</a> or the <a href=\"https://github.com/hapifhir/org.hl7.fhir.core/pull/358/commits/5be73ff9c55c5469b923a0a5b3b221d7e3962b48\">exact commit</a>) renamed <code>org.hl7.fhir.utilities.cache</code> to <code>org.hl7.fhir.utilities.npm</code>.  If you'd like to take a stab at updating the imports in the code I'd be happy to take a PR!</p>",
        "id": 219380438,
        "sender_full_name": "Reece Adamson",
        "timestamp": 1607539824
    },
    {
        "content": "<p>Alright, I'll take a stab in my copious free time.  Dredge up atrophied<br>\njava skills...</p>",
        "id": 219381581,
        "sender_full_name": "Marvin Greenberg",
        "timestamp": 1607540309
    },
    {
        "content": "<p>OK <span class=\"user-mention\" data-user-id=\"197651\">@Reece Adamson</span> afaict all test passing (for me locally) although the ci/cd to travis seems stuck.  No promises bu the changes seemed simple enough<br>\n<a href=\"https://github.com/inferno-community/fhir-validator-wrapper/pull/28\">https://github.com/inferno-community/fhir-validator-wrapper/pull/28</a></p>",
        "id": 219481355,
        "sender_full_name": "Marvin Greenberg",
        "timestamp": 1607611580
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"267676\">@Marvin Greenberg</span> Awesome, looks good from what I see!  I'll give it a test drive later today so we can get this in. <span aria-label=\"party ball\" class=\"emoji emoji-1f38a\" role=\"img\" title=\"party ball\">:party_ball:</span></p>",
        "id": 219501705,
        "sender_full_name": "Reece Adamson",
        "timestamp": 1607619547
    },
    {
        "content": "<p>I see community edition uses (fhir_models (4.1.1) gem. However  when I try to validate any invalid json, i am not seeing any errors or warnings from this gem. If i provide the same invalid json to validator_cli.jar it catches those errors and displays as intended. Is there something needs to be done with this gem?<br>\nTo validate cloned '<a href=\"https://github.com/fhir-crucible/fhir_models\">https://github.com/fhir-crucible/fhir_models</a>' and provided an invalid json from console. No errors for the attached invalid json. <a href=\"/user_uploads/10155/nKRKQBkaje-FeQgb-66zSw49/patient.json\">patient.json</a></p>",
        "id": 228403039,
        "sender_full_name": "ashoka p",
        "timestamp": 1614689045
    },
    {
        "content": "<p>I get the following output: </p>\n<div class=\"codehilite\"><pre><span></span><code>[2] pry(main)&gt; patient = FHIR.from_contents(json)\n[3] pry(main)&gt; patient.validate\n=&gt; {&quot;text&quot;=&gt;[{&quot;div&quot;=&gt;[&quot;Narrative.div: &lt;div xmlns=\\&quot;http://www.w3.org/1999/xhtml\\&quot;&gt;&lt;/p&gt;&lt;/div&gt; is not a valid xhtml&quot;]}]}\n[4] pry(main)&gt; patient.valid?\n=&gt; false\n</code></pre></div>\n<p>It isn't picking up the extra elements though as an error, which does seem like an issue.</p>\n<p>Note that we don't typically use the <code>fhir_models</code> validation within Inferno, and instead use the HL7 validator (there is a configuration flag to choose which validator to use).  fhir_models validation has known bugs. We chose to simply reuse the HL7 validator initially so we could focus on other things, but I would like to circle back and invest time in our fhir_models validator because using an external service adds complexity.</p>",
        "id": 228414548,
        "sender_full_name": "Robert Scanlon",
        "timestamp": 1614694053
    },
    {
        "content": "<p>Thanks <span class=\"user-mention\" data-user-id=\"192576\">@Robert Scanlon</span> . Yes i deliberately altered div and only that gets flagged as error from fhir-models. With correct div, i get patient.valid? as true. So atleast for now we cannot rely on fhir-models as a validator.</p>",
        "id": 228535974,
        "sender_full_name": "ashoka p",
        "timestamp": 1614747066
    },
    {
        "content": "<p>It is a tradeoff on how thorough you would like your validation to be vs. how much work you want to do adding another tool outside of Ruby.  In the short term, if you need validation to be fairly thorough, then I agree that you shouldn't rely on fhir-models for validation.  Hopefully we can fix that though.</p>",
        "id": 228595910,
        "sender_full_name": "Robert Scanlon",
        "timestamp": 1614780170
    }
]