[
    {
        "content": "<p>Hi,</p>\n<p>My team and I are using HAPI FHIR 5.1.0 with R4.<br>\nFor Encounters where one or more QuestionnaireResponses refer to the Encounter, we get a NullPointerException while doing this search:<br>\n<a href=\"http://host:port/fhir/Encounter?_id=XXX&amp;_revinclude=*&amp;_include=*\">http://host:port/fhir/Encounter?_id=XXX&amp;_revinclude=*&amp;_include=*</a></p>\n<p>{<br>\n    \"resourceType\": \"OperationOutcome\",<br>\n    \"issue\": [<br>\n        {<br>\n            \"severity\": \"error\",<br>\n            \"code\": \"processing\",<br>\n            \"diagnostics\": \"Failed to call access method: java.lang.NullPointerException\"<br>\n        }<br>\n    ]<br>\n}</p>\n<p>I can reproduce the error on my local jetty server and here's a very small snippet from the log:</p>\n<p>Caused by: java.lang.NullPointerException<br>\n    at ca.uhn.fhir.rest.api.server.storage.ResourcePersistentId.hashCode(ResourcePersistentId.java:55)</p>\n<p>I believe I know why we get the NullPointerException.<br>\nOur QuestionnaireResponses doesn't contain a literal reference to a Questionnaire, but a reference by a canonical url as per definition.<br>\nWhen looking in the database the TARGET_RESOURCE_ID (Persistent ID) is NULL in these cases and instead TARGET_RESOURCE_URL is populated in schema HFJ_RES_LINK.</p>\n<p><a href=\"/user_uploads/10155/c1SSB9j1icYl-p5GV85dmAgN/image.png\">image.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/10155/c1SSB9j1icYl-p5GV85dmAgN/image.png\" title=\"image.png\"><img src=\"/user_uploads/10155/c1SSB9j1icYl-p5GV85dmAgN/image.png\"></a></div><p>My questions: </p>\n<p>Are any of you familiar with this error?</p>\n<p>Does anyone of you know if this error also exists in HAPI FHIR 5.3.0? (I can't find anything in the HAPI FHIR changelog)<br>\nFYI: I have tried to reproduce the error on the server <a href=\"http://hapi.fhir.org\">hapi.fhir.org</a>, but I receive a valid response when creating the ressources and doing the search here.</p>",
        "id": 234319885,
        "sender_full_name": "Ann Merete Duedal Jensen",
        "timestamp": 1618318793
    },
    {
        "content": "<p>I would recommend to update latest stable - being 5.3.0 for now</p>",
        "id": 234321355,
        "sender_full_name": "Jens Villadsen",
        "timestamp": 1618319353
    },
    {
        "content": "<p>That what also my thought. Just wanted to check if someone knew if the problem still exists in 5.3.0.</p>",
        "id": 235153108,
        "sender_full_name": "Ann Merete Duedal Jensen",
        "timestamp": 1618825184
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"191319\">@James Agnew</span>  Do you know if this issue has been fixed in 5.3.0? We cannot deduce it from the changelog</p>",
        "id": 235489896,
        "sender_full_name": "Signe Hejgaard Kristoffersen",
        "timestamp": 1619002791
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"256845\">@Signe Hejgaard Kristoffersen</span>  <span class=\"user-mention\" data-user-id=\"191319\">@James Agnew</span>  - Not sure if this is related but in HAPI 5.0.2 (used by cqf-ruler) we were seeing NullPointerExceptions when performing .../ValueSet/&lt;valueSetId&gt;/$expand operations.   This seemed to happen after the CodeSystem associated with the ValueSet was expanded.   We recently switched to HAPI 5.3.0 and this problem went away.  (As I understand it, indices for CodeSystem expansions were stored on the file system in pre-5.3.0 HAPI but with 5.3.0 they are now stored in the database; maybe James could clarify or point us to the release notes that indicates this change.)</p>",
        "id": 235491258,
        "sender_full_name": "John Silva",
        "timestamp": 1619003413
    }
]